### PR TITLE
#162725216: Integrate sass into the application

### PR DESCRIPTION
**Pull request by mariamiah**
#### What does this PR do?
* Sets up SASS processing on the client
#### Description of Task to be completed?
* Install and setup sass pre-processing on the application to enables the use of both .scss and .css files on the client
#### How should this be manually tested?
* fetch this branch by running `git fetch origin ch-integrate-sass-processing-162725216` in your terminal
* check out into the branch using `git checkout ch-integrate-sass-processing-162725216`
* run `yarn install` to install the dependencies
* run `yarn start` to start the development server
* navigate to localhost:8000
* view the sass effect on the different page elements
#### What are the relevant pivotal tracker stories?
[Starts #162725216](https://www.pivotaltracker.com/n/projects/2232225/stories/162725216https://www.pivotaltracker.com/n/projects/2232225/stories/162725216https://www.pivotaltracker.com/n/projects/2232225/stories/162725216)

### CODE REVIEW

**Review by d-rita — COMMENTED** [review]
I notice you have some conflicts. Please resolve those.

**Comment by RrNn** [comment]
Good work. I would rather we have a file `variables` and import it into `styles.scss` rather than having the `variables` followed by `class names` or `html` elements that use the colors.

**Comment by armstrongsouljah** [comment]
@mariamiah. Please look into the conflicts above and  resolve them.

**Comment by mariamiah** [comment]
> Good work. I would rather we have a file `variables` and import it into `styles.scss` rather than having the `variables` followed by `class names` or `html` elements that use the colors.

@RrNn please provide more clarification

**Pull request closed without merging**
