### PR TITLE
#162725215 Setup react router.

### PR DESCRIPTION
**Pull request by armstrongsouljah**
#### What does this Pr do?
Adds an implementation that will enable routing with the application using the react router dom library.

#### Description of the task to be implemented?
- Install and configure the router creating a dummy route for login and the "/" page to test the configuration.
- Create a components and views file structure where view pages are in the views folder but individual - components are in the components folder.

#### How can this be manually tested?
- Fetch this branch to your local machine by running `git fetch origin ch-setup-react-router-162725215`
- Checkout to this branch by running` git checkout ch-setup-react-router-162725215`
- Install project dependencies by running `yarn install`
- Start the development server by running `yarn start`
- After the web browser opens, navigate to `/login or /` by clicking the links.

#### Screenshots if necessarry.
screenshot 2019-02-12 at 12 29 06

### CODE REVIEW

**Review by MuhweziDeo — DISMISSED** [review]
Looks good to me

**Comment by RrNn** [comment]
The description needs tweaking a bit. Since we are using **yarn**, we should do `yarn install` or just `yarn` to install the packages, then run `yarn start` to start the dev server. Update the `How can this be manually tested?` section in the description.

**Comment by armstrongsouljah** [comment]
@RrNn Pr description has been updated to yarn instead of **npm**.

**Review by calvinpete — APPROVED** [review]
LGTM

**Comment by mariamiah** [comment]
Tested it and it works okay, good job @armstrongsouljah

**Review by mariamiah — APPROVED** [review]

**Review by kdaglas — APPROVED** [review]
lgtm

**Review by d-rita — COMMENTED** [review]
The links work. LGTM

**Pull request merged**
