### PR TITLE
#162725217 Run Code Climate Test coverage

### PR DESCRIPTION
**Pull request by calvinpete**
#### What does this PR do?
This PR runs the code climate test coverage after passing tests from circleci.

#### Description of Task to be completed?
- Create a .circleci folder and inside of that create a config.yml file
- Configure CircleCi
- Set up the README badge

#### How should this be manually tested?
Trigger build on circleci.

#### What are the relevant pivotal tracker stories?
[#162725217](https://www.pivotaltracker.com/story/show/162725217)

#### Screenshots
image
#### Please note that the badges are for develop thus failing
image

### CODE REVIEW

**Comment by armstrongsouljah** [comment]
I followed up on the build and all things seem to check out. Good work @calvinpete !

**Review by mariamiah — APPROVED** [review]
Works fine

**Review by armstrongsouljah — APPROVED** [review]
Build runs and reports coverage to codeclimate. Good work @calvinpete .

**Review by MuhweziDeo — APPROVED** [review]
LGTM

**Comment by d-rita** [comment]
LGTM

**Pull request merged**
