### PR TITLE
#162725222:Users should be able to view and edit their profiles

### PR DESCRIPTION
**Pull request by mariamiah**
#### What does this PR do?
Implements the feature that allows users to view and edit their profiles.

#### Description of Task to be completed?
* Users should be able to amend/edit their profiles depending on the change of preference to the full disclosure of the individual user

#### How should this be manually tested?
* Fetch and checkout into this branch with `git fetch origin ft-display-user-profile-162725222`
* Checkout into this branch by running `git checkout ft-display-user-profile-162725222`
* Install dependencies and start the app with `yarn install && yarn start`
* Navigate to the `/profile` endpoint and view profiles

#### What are the relevant pivotal tracker stories?
[#162725222](https://www.pivotaltracker.com/n/projects/2232225/stories/162725222)

### CODE REVIEW

**Comment by MuhweziDeo** [comment]
@mariamiah  am unable to view articles

**Comment by mariamiah** [comment]
> @mariamiah am unable to view articles

yes @MuhweziDeo the PR is actually still work in progress as I wait for the login feature to be merged so we can have access to the token

**Comment by MuhweziDeo** [comment]
@mariamiah looks good except for the UI maybe tweak it a little more

**Comment by d-rita** [comment]
@mariamiah When i try to submit my edited profile, I end up getting a 403 message even though there is a token set.  What could be the cause of that?

**Comment by mariamiah** [comment]
> @mariamiah When i try to submit my edited profile, I end up getting a 403 message even though there is a token set. What could be the cause of that?

403 means forbidden because you have not logged in, may i please know how you have set your token? ..finally try using social login youl be good to go

**Pull request merged**
