### PR TITLE
#162725223 User should be able to create, update or delete an article

### PR DESCRIPTION
**Pull request by calvinpete**
#### What does this PR do?
This PR implements functionality for creating, updating and deleting articles

#### How should this be manually tested?
* Fetch and checkout into this branch with `git fetch origin ft-crud-articles-162725223 && git checkout ft-crud-articles-162725223`
* Setup dependencies with `yarn install && yarn start`
* Navigate to `/editor` endpoint to create an article.
* Navigate to the `/article/article-slug` endpoint of viewing a single article then you can edit or delete the article you have created.
* In case you can not delete or edit an article then you aren't the author of the article

#### What are the relevant pivotal tracker stories?
[#162725223](https://www.pivotaltracker.com/story/show/162725223)

### CODE REVIEW

**Comment by malfahad** [comment]
@calvinpete  Please rebase to remove conflicts

**Comment by RrNn** [comment]
@calvinpete Editing an article doesn't seem to work.

**Review by malfahad — DISMISSED** [review]
LGTM

**Review by malfahad — APPROVED** [review]
LGTM

**Review by MuhweziDeo — APPROVED** [review]
LGTM great work @calvinpete cc @RrNn

**Review by mariamiah — APPROVED** [review]
LGTM

**Pull request merged**
