### PR TITLE
#162725212 Setup redux

### PR DESCRIPTION
**Pull request by MuhweziDeo**
####  What does this PR do?
Setting up redux for the react project

####  Description of Task to be completed?
- install dependencies for redux 
- create reducers and actions
- create a redux store file
- Wrap the main component around Provider 

####  How should this be manually tested?
- fetch this branch by running `git fetch origin ch-setup-redux-162725212` in your terminal
- check out into the branch using `git checkout ch-setup-redux-162725212`
- run `yarn install` to install dependencies
- run `yarn start` to start the development server
- navigate to localhost:8080
- click inspect to open Devtools for browser ensure you have React and redux dev tools installed in your browser of choice
- open react dev tools to view redux store

####  What are the relevant pivotal tracker stories?
[Starts #162725212](https://www.pivotaltracker.com/story/show/162725212)
####  Screenshots (if appropriate)

screen shot 2019-02-12 at 11 38 34 am

screen shot 2019-02-12 at 11 38 49 am

### CODE REVIEW

**Comment by RrNn** [comment]
Good work @MuhweziDeo . Remove the `Redux` dir, it's not necessary, just put the `actions` and `reducers` in `src`. Also, rename the folders to `actions`, `reducers`, etc, there is no need to Pascal case dir names.

**Comment by MuhweziDeo** [comment]
> Good work @MuhweziDeo . Remove the `Redux` dir, it's not necessary, just put the `actions` and `reducers` in `src`. Also, rename the folders to `actions`, `reducers`, etc, there is no need to Pascal case dir names.

more clarity on why its unneccessary

**Comment by RrNn** [comment]
It's verbose, we are already using Redux and the deeply nested sub dir of `Redux` is redundant. We don't have to nest our reducers and actions.

**Comment by armstrongsouljah** [comment]
@MuhweziDeo  The entry component is no longer `App/>` but `<Routes />`, so you'll have to rebase and wrap the provider around that.

**Comment by MuhweziDeo** [comment]
> It's verbose, we are already using Redux and the deeply nested sub dir of `Redux` is redundant. We don't have to nest our reducers and actions.

cool @RrNn

**Comment by RrNn** [comment]
As you resolve the conflicts, you can go ahead and move the testReducer into its own file then import that into `RootReducer`. This will mimic how our reducers are going to be imported from their respective files. Also, you could rename the  `RootReducer` to `index` so that we just import all reducers to it and import from the `reducers` dir to our components that will need connecting. This will be a better structure.

**Review by malfahad — APPROVED** [review]

**Comment by kdaglas** [comment]
@MuhweziDeo, this is nice though your PR testing requires some revision, you need to add the fetching of the branch and checking it out

**Review by kdaglas — APPROVED** [review]
lgtm

**Comment by MuhweziDeo** [comment]
> @MuhweziDeo, this is nice though your PR testing requires some revision, you need to add the fetching of the branch and checking it out

cool updated

**Review by calvinpete — APPROVED** [review]
LGTM

**Pull request merged**
