### PR TITLE
#162725219 Users should be presented with a reset password link

### PR DESCRIPTION
**Pull request by malfahad**
#### What does this PR do?
Introduces functionality for the users to reset their passwords using a valid email address registered with authors haven.

#### Description of Task to be completed?
- Create relevant views, components, actions, and reducers.
- Write relevant unit tests and integration tests.
-  Design layouts with the CSS framework.

#### How should this be manually tested?
- Fetch and checkout into this branch with `git fetch origin ft-password-reset-162725219 && git checkout ft-password-reset-162725219`
- Install dependencies and start the app with `yarn install && yarn start`
- Navigate to the `/password-reset` endpoint and recover your password

#### What are the relevant pivotal tracker stories?
[#162725219](https://www.pivotaltracker.com/story/show/162725219)

### CODE REVIEW

**Comment by MuhweziDeo** [comment]
@malfahad the `git checkout and fetch` command has some issues there are **%%** instead of **&&**
other than that the form works very well and UI is very clean, plus redux actions gets dispatched

**Review by MuhweziDeo — DISMISSED** [review]
Tests are passing, UI is clean and hits the backend endpoint, Redux actions are trigged 
@malfahad @RrNn **LGTM**

**Review by MuhweziDeo — APPROVED** [review]
LGTM

**Review by mariamiah — APPROVED** [review]
LGTM

**Review by calvinpete — APPROVED** [review]
LGTM

**Pull request merged**
