### PR TITLE
164241177 Users should visit profiles

### PR DESCRIPTION
**Pull request by malfahad**
#### What does this PR do?
This PR introduces functionality for authenticated users to visit other users profiles.
#### Description of Task to be completed?
As an authenticated user, I should be able to visit any single profile on authors haven. this will allow me to follow or unfollow that profile.

#### How should this be manually tested?
- Fetch and checkout into this branch with `git fetch origin ft-visit-profile-164241177 && git checkout ft-visit-profile-164241177`
- Install dependencies and start the app with `yarn install && yarn start`
- login to your author's haven account.
- navigate to your profile with `/profile`
- navigate to another users profile with `/profiles/:username`

#### What are the relevant pivotal tracker stories?
[#164241177](https://www.pivotaltracker.com/story/show/164241177)

### CODE REVIEW

**Comment by mariamiah** [comment]
@malfahad Please rebase

**Review by MuhweziDeo — DISMISSED** [review]
LGTM

**Review by calvinpete — DISMISSED** [review]
LGTM

**Comment by RrNn** [comment]
@malfahad , I can't seem to see my profile.

**Comment by malfahad** [comment]
@RrNn   , Getting user profiles works for authenticated users. you shall need to login first to see your profile and other users profiles.

**Comment by RrNn** [comment]
Okay, I get you

**Pull request merged**
