### PR TITLE
 #164243861 setup testing with travis

### PR DESCRIPTION
**Pull request by malfahad**
#### What does this PR do?
This chore switches from circle CI to Travis as the default CI testing environment.

#### What are the relevant pivotal tracker stories?
[#164243861](https://www.pivotaltracker.com/story/show/164243861)

### CODE REVIEW

**Review by armstrongsouljah — APPROVED** [review]
Build is running good work @malfahad.

**Review by calvinpete — APPROVED** [review]
LGTM

**Review by kdaglas — APPROVED** [review]
lgtm

**Comment by d-rita** [comment]
@malfahad Maybe format the pr according to the engineering playbook.

**Comment by malfahad** [comment]
@d-rita thanks for the feedback. I have implemented the changes.

**Review by d-rita — APPROVED** [review]
LGTM

**Pull request merged**
