### PR TITLE
#162725211 Setup an empty react project

### PR DESCRIPTION
**Pull request by kdaglas**
### What does this PR do?
This PR is to set up a react project using webpack and babel

### Description of Task to be completed?
- install node
- set up webpack and initialize npm
- add installation of babel

### How should this be manually tested?
- fetch this branch using `git fetch origin ch-setup-react-162725211`
- checkout into that branch `git checkout ch-setup-react-162725211` 
- install the dependencies that are required using `yarn install`
- start the app `yarn start`

#### What are the relevant pivotal tracker stories?
[#162725211](https://www.pivotaltracker.com/story/show/162725211)

### CODE REVIEW

**Comment by MuhweziDeo** [comment]
Hound got u covered @kdaglas

**Review by armstrongsouljah — COMMENTED** [review]
In `App.jsx` You're naming the component `Teaser` as the entry component. Wouldn't it be better you name it **App** for consistency?

**Comment by mariamiah** [comment]
@kdaglas good work though it would be better if you added `package-lock.json` to your .gitignore file

**Review by calvinpete — COMMENTED** [review]
@kdaglas Please note that JSX is not allowed in .js files. I suggest you rename the index.js to index.jsx

**Comment by malfahad** [comment]
@calvinpete  `.jsx` naming  is for React components please see [guide](https://github.com/airbnb/javascript/tree/master/react#naming) `index.js` is the entry point of the app. I think we can keep it as `.js`

**Comment by kdaglas** [comment]
@armstrongsouljah i have changed the name to App, and @calvinpete i have made the eslint to allow both js and jsx files and @mariamiah i have added the package-lock file in the gitignore

**Review by mariamiah — DISMISSED** [review]
LGTM

**Review by MuhweziDeo — DISMISSED** [review]
LGTM

**Review by malfahad — DISMISSED** [review]

**Review by armstrongsouljah — DISMISSED** [review]
LGTM!

**Review by calvinpete — DISMISSED** [review]
LGTM

**Comment by RrNn** [comment]
Good work, I would like us to use `.js` extensions for all our files, so lets do `App.js` instead of `.jsx`.

**Comment by mariamiah** [comment]
@RrNn , According to the airbnb eslint [style guide](https://github.com/airbnb/javascript/tree/master/react#naming) , we are actually expected to have the .jsx files there otherwise the linter will complain

**Pull request merged**
